---
abstract: 'Simple tree widget for Tickit'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-Tree
requires:
  Tickit: 0.12
  parent: 0
version: 0.001
