---
abstract: 'Terminal tree widget'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::Fatal: 0.010
  Test::More: 0.98
  Test::Refcount: 0.07
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-Tree
requires:
  Mixin::Event::Dispatch: 1.000
  Term::TermKey: 0
  Tickit: 0.37
  Tree::DAG_Node: 1.16
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tickit-Widget-Tree
  homepage: http://search.cpan.org/dist/Tickit-Widget-Tree/
version: 0.100
